<?php
include('../global.php');
?>

<h1><center><strong>Privacy Policy</strong></center></h1>
<h1><left><strong>Information about Avatar Central</strong></left></h1>
<p><center> Avatar Central is an online community created to give users a social experience to hang out, customize their avatar in many different ways, and overall; for fun! We here at Avatar Central want <strong> everyone </strong> to have an awesome experience! We are a small community slowly growing into something big! - The privacy policy is here to show you how we use your information and our rules here at Avatar Central.</center></p>

<h1><left><strong>How Avatar Central functions</strong></left></h1>
<p><center> It starts when a user signs up for Avatar Central. He/she gets their own avatar and account. They start with a certain amount of our currency, Bucks and Gold Coins, they can use Bucks and Gold Coins to purchase items for their avatar to make themselves look awesome. If they do not like the clothes in the store, they can make their own! They can upload items to the shop for a hope of getting them published. The user can also trade their gold coins to receive more bucks; or trade in their bucks to receive more gold coins. The user can also purchase special items called Limiteds, Limiteds are items that have a limit on stock and are more valued than normal items. The user can even collect limited serial numbers, serial numbers are the items number, the first item sold gets serial one, second gets serial two, and so on. The user can show off their items on the forum or public chat, a wip feature. On the forum the user can create threads and start a conversation on various different topic sub-forums or just join in a conversation. The user can meet friends on the forum and hang out with them. The user can send friend requests by going to another user's account and clicking "Send friend request". If he/she wants to have a group of friends in their own small community, then the user can look into "Communities". Communities are groups that users can join to hang out in and talk to each other. You can express yourself among various other group members and have an awesome conversation, or a classy one. The user's choice. The user can also participate in "Worlds" another work in progress feature. Worlds are where users can play and interact with each other on a new level. They can show off their items in a new way and chat while playing games. The user can create their own world to play in, and maybe friends or other users will take interest in it and join. The user can do the opposite and join someone else's world to though! Communities can also have their own worlds for meetings/parties. This can enhance social rating by a jumpstart! It's so easy to start that big fun cycle, the user can be <strong> you </strong>, just sign up to Avatar Central today. It's easy!  </strong></center></p>

<h1><left><strong>Requested Information</strong></left></h1>
<p><center>Avatar Central does not allow guest accounts, as there is no need for them at the moment. In order to purchase clothing, interact with users, and do all of the other possibilities of Avatar Central you must register an account. Your password or personal information will NOT be shared with any 3rd parties unless you make purchases with credited information. All users are required to put in an e-mail address. If your e-mail address is fake then you will never receive notifications or newsletters from Avatar Central in your feed, neither will you be able to recover your accounts if lost. If your are under the age of 13 (12 or younger) we request that you get a parent to use their e-mail address to make your experience safer. You are not required to add a REAL e-mail adress if you do not like, you just will not receive news, etc. If you are a parent that is concerned about your child being exposed to inappropriate content, then we will ensure you that we have filters and moderators that work to stop all of the inappropriate content flow. If you do have any complaints then send us an e-mail at <a href="mailto:info@avatarlife.pe.hu">info@avatarlife.pe.hu</a> ~ if any curse words break past our filter we quickly add the word to our filter and work to find ways to stop filter passing to keep our community as clean as possible! Just note that we cannot be 100% clean of inappropriate content, we cannot ensure that your child will not see any inappropriate content, we hope you appreciate our honesty with you. We currently do not offer a membership, but the rules are already that children under 13 need to have your parent's billing information, we will never store full credit card information.</center></p>

<h1><strong><left>Collected Information</strong></left></h1>
<p><center> We collect a small amount of information from users, we often collect things that can help us identify you better, we never give out your information, it is very safe. We often collect user's names that they provide on sign-up, please note that you are not required to put your real name, we can use it to e-mail your parents (if your accounts e-mail is your parent's e-mail) and they will know your name better than a username you picked on the website, most likely. We also ask that you do not use your real name as a username, we do not want you to endanger yourself or anyone else. We sometimes collect polls that have to do with are users having a good experience or not, etc to keep track of data. We keep track of the amount of users joined to. This is just stuff that helps us analyze data and make your experience better.</center></p>

<h1><strong><left>Information Sharing</strong></left></h1>
<p><center> We do not share your information with 3rd parties, and if we do it is not in any ways that will effect your information and privacy, we will <strong> never </strong> sell your information to 3rd parties. There is not much to put here at the moment because there is not much we do that can jeopardize your information in a way, or anything that could concern you.</center></p>

<h1><strong><left>Security & Privacy</strong></left></h1>
<p><center>Please note that we do not collect any of your information other than your Name and E-mail (+ your IP) - Your name is also not required if you do not want to give it to us at sign up. We do not yet do any credit card transactions so you do not have to worry about credit card security yet. Please note that if you post any of your personal information on our forums, in messages, or in communites then that information can be read or collected by our community. Please be wise about what you post. If your child has posted personal information and you want to discuss with us about this e-mail us at <a href="mailto:info@avatarlife.pe.hu">info@avatarlife.pe.hu</a> - In some cases we cannot remove your child's information, if you need to know why we will include an answer also.</center></p>

<h1><strong><left>Contact Information</strong></left></h1>
<p><center> If you have any questions, concerns, or comments regarding our Privacy Policy, you can contact us with the following information.

E-mail: <a href="mailto:info@avatarlife.pe.hu">info@avatarlife.pe.hu</a>